FROM python:3.9

WORKDIR /code

# Copie et installation des dépendances
COPY ./requirements.txt /code/requirements.txt
RUN pip install --no-cache-dir --upgrade -r /code/requirements.txt

# Copie de tout le projet (y compris le dossier templates/ et les fichiers .pkl)
COPY . .

# Commande pour lancer ton application Flask
CMD ["python", "app.py"]